"""user_coupons

Revision ID: 8cf455aabd0d
Revises: dfaa470fc553
Create Date: 2026-09-26 17:15:55.657912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cf455aabd0d'
down_revision: Union[str, Sequence[str], None] = 'dfaa470fc553'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_coupons',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('coupon_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['coupon_id'], ['coupons.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'coupon_id', name='uq_user_coupon')
    )
    op.create_index(op.f('ix_user_coupons_coupon_id'), 'user_coupons', ['coupon_id'], unique=False)
    op.create_index(op.f('ix_user_coupons_id'), 'user_coupons', ['id'], unique=False)
    op.create_index(op.f('ix_user_coupons_user_id'), 'user_coupons', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_coupons_user_id'), table_name='user_coupons')
    op.drop_index(op.f('ix_user_coupons_id'), table_name='user_coupons')
    op.drop_index(op.f('ix_user_coupons_coupon_id'), table_name='user_coupons')
    op.drop_table('user_coupons')
    # ### end Alembic commands ###
